### ISSUE TITLE
Link to Google Maps on show_map.php does not work

### ISSUE THREAD

**Issue by hhkauppi** [matstroeng/doma#16]
If you click on the small map picture on the top right corner of the show_map.php page, it tries to locate the URL of the DOMA instance on Google Maps instead of displaying the route there as I assume it was supposed to do.

Example from reference site dxdeluxe.se:
The page http://www.dxdeluxe.se/linnekartparmen/show_map.php?user=Osamoborac&map=5637 opens https://www.google.com/maps?q=http://www.dxdeluxe.se/linnekartparmen/export_kml.php?id%3D5637%26format%3Dkml&language=sv

**Comment by hhkauppi** [comment]
After I implemented the https changes the loading of the small picture in the first place is not working properly anymore, but I have not completed the root cause analysis for this yet.

**Comment by runerys** [comment]
I've submitted a PR for this: https://github.com/matstroeng/doma/pull/24

**Comment by runerys** [comment]
Even with the fix, You have to configure the api key to enable access to the static maps api. But the error message You get in the browser console is quite explanatory.
