### ISSUE TITLE
Error include/quickroute_jpeg_extension_data.php on line 728 for some maps

### ISSUE THREAD

**Issue by jan-gerard** [matstroeng/doma#18]
Some maps (for example the map image on http://jgeo.nl/quickroute/show_map.php?user=jg&map=136), give errors:
PHP Warning:  Invalid argument supplied for foreach() in xxx/include/quickroute_jpeg_extension_data.php on line 728
I suppose that this map contains a legacy version of the track data embedded in the jpeg extension data area. But I think that the doma php code should be robust for that, either ignoring the contents or handling it otherwise, but not give an error in the server logs.
Maybe just a `if (!is_null($handles)) {` around it?

**Comment by runerys** [comment]
I've submitted a PR fixing this: https://github.com/matstroeng/doma/pull/23
