### ISSUE TITLE
Leaflet intergration, Coordinates only saving after saving once before

### ISSUE THREAD

**Issue by yani66** [matstroeng/doma#33]
Hi, I integrated Leaflet in to my DOMA.
Essentially it should work like the Google Maps integration, with some extra features.
Like setting coorinates without exporting from QuickRoute. 
I do this with a map on the edit_map.php.
![image](https://github.com/matstroeng/doma/assets/59028071/85cd37c4-a95e-4278-9412-b0a88413793a)
When editing a map it works just fine and it get's saved to the database, but when adding a new map it doesn't work.
________________________________________________________________________________________________________________________________________

The coordinates get temporarily saved in an hidden input:
```
<input type="hidden" name="lat" id="lat" value="<?php print hsc($map->MapCenterLatitude)?>">
<input type="hidden" name="lng" id="lng" value="<?php print hsc($map->MapCenterLongitude)?>">
```
then when saved handed to the controller like all other values after  `if(isset($mapID)) {...} else{...}`:
```
$map->MapCenterLatitude = $lat;
$map->MapCenterLongitude = $lng;
```

Thanks for any help!
Yannis

**Comment by hhkauppi** [comment]
I did not have time to check the code base, but I was looking at it some time ago for a similar purpose and if I recall correctly DOMA reads the coordinates only from the metadata in the picture file when adding a new map. QuickRoute adds the coordinates to the metadata of the JPEG file and this information is retrieved when the map is saved to DOMA. I have been planning to create an alternative way to enter the data when adding maps (which would allow georeferencing files with routegadget online tools), but have not had the time to get this done. So if anyone is interested in working on this, I would be happy to participate.

**Comment by yani66** [comment]
With my integration you can add coordinates without QuickRoute. Just click the position on the map when editing a map. The only problem is that it only saves the coordinates to the database when the map was saved once beforce.

**Comment by yani66** [comment]
I looked at it again and could figure out what the problem was.
It was just setting the variable to `null` afterwards because of the missing meta data.
Thanks for your help.
