### ISSUE TITLE
doma doesn't work with php 7

### ISSUE THREAD

**Issue by vincent3569** [matstroeng/doma#5]
all is in the title: doma doesn't work with php 7

**Comment by matstroeng** [comment]
That's true. Unfortunately, at the moment I don't have the time to make efforts to migrate to PHP 7. Maybe someone else?

**Comment by hhkauppi** [comment]
Are you able to provide any insights into what the key issues are for reaching PHP 7 compatibility?

**Comment by bjugan** [comment]
I think it's only some minor changes in two files. I'm doing some testing and will commit the changes when the testing is done.

**Comment by bjugan** [comment]
Just to warn you, i just made my first pull request ever on Github... :)

Halden SKs DOMA is now running on php 7.1 og MySQL 5.7.21. (https://doma.haldensk.no/) It's seems like it's working fine. I have also successfully uploaded a map from QuickRoute.

I testet php 7.2 as well, but got som errors. Will perhaps look into that later.

**Comment by vincent3569** [comment]
hi
@matstroeng is there a way to merge the pull request to make doma compatible with php 7?
thanks in advance
